"""4-cell comparison report — Phase 3.2.4.3.

Renders the four ``CellRunResult``s into a markdown report:

  * 4×5 metrics table (cell × Sharpe / E / walk-forward / max DD /
    total trades)
  * per-cell PASS/FAIL flag against the Track B thresholds
  * delta-vs-baseline column for the three non-baseline cells
    (raw difference; significance testing is Phase 3.3 territory)
  * "What would falsify Formülasyon A" section restating the
    hypothesis the 4-cell experiment is designed to test

decision (markdown output):
  The acceptance doc explicitly says markdown. Renders cleanly in
  GitHub PRs, slack snippets, and any plain-text review tool. JSON
  / parquet structured output is deferred until cross-run
  programmatic comparison shows up as a need.

decision (baseline = tier1_single):
  The acceptance doc names the baseline explicitly:
  '(Tier-1, single)'. The Formülasyon A hypothesis is that
  '(Tier-2, fusion)' beats every other cell — including the
  baseline. Other deltas help diagnose partial wins (only Tier-2,
  only fusion). If a future runner uses different cells, baseline
  is the first cell in the list.

decision (delta = raw difference, no t-test):
  Phase 3.3 will pick a multiple-comparisons-correction approach
  (Bonferroni vs Benjamini-Hochberg vs nested cross-validation);
  Phase 3.2.4 just shows the difference. Premature significance
  tests would lock us into the wrong correction; raw deltas are
  the honest middle ground.

decision (None values render as 'n/a' in the table):
  Sharpe with < 30 trades, walk-forward with < N trades. The
  delta column for an n/a baseline is also 'n/a' (no meaningful
  difference can be computed). Documented in the report's
  preamble so a reader knows what 'n/a' means.
"""

from __future__ import annotations

import io
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from uoa_detector.backtest.cell_runner import CellRunResult
    from uoa_detector.backtest.metrics import BacktestMetrics


_FALSIFICATION_TEXT = """\
## What would falsify Formülasyon A

Formülasyon A is the combinatorial hypothesis: a real edge requires
**`(Tier-2, fusion)`** to materially beat the other three cells. Each
of the following partial outcomes **rejects** the combinatorial
hypothesis even if individual signals look interesting:

  - **Only `(Tier-2, single)` beats baseline.** The fusion layer
    isn't pulling its weight; whatever Tier-2 signal exists works
    at single-source. The hypothesis "fusion is necessary" fails.
  - **Only `(Tier-1, fusion)` beats baseline.** The Tier-2
    universe isn't where the edge lives; fusion alone on the
    anchor universe is enough. The hypothesis "Tier-2 is
    necessary" fails.
  - **Both single-source cells beat both fusion cells.** Fusion
    is a net negative — it's filtering out signal, not noise.
    Combinatorial hypothesis is decisively rejected.
  - **Tier-2 fusion does NOT materially beat Tier-1 fusion AND
    Tier-2 single.** The combinatorial gain doesn't exist; the
    edge attribution can be explained by the marginal contribution
    of fusion or universe alone, not their interaction.

A strict "Tier-2 fusion materially beats every other cell" outcome
is what would let us proceed to Phase 3.3's first real backtest
with confidence in the Track B + Formülasyon A framing. Anything
weaker is a signal to revise the hypothesis before risking capital.
"""


def render_4cell_comparison_report(
    results: tuple[CellRunResult, ...],
    *,
    baseline_cell_name: str = "tier1_single",
) -> str:
    """Render the 4-cell run results into a markdown comparison report.

    Returns a markdown string. Caller writes it to disk (the CLI
    does this; ``tests/integration/`` writes to ``tmp_path``).

    The baseline cell is the first cell in ``results`` if no name
    matches ``baseline_cell_name``; this lets future N-cell runners
    pick a different baseline without API changes.
    """
    if not results:
        msg = "render_4cell_comparison_report: results tuple is empty"
        raise ValueError(msg)

    # Find the baseline; fall back to the first result.
    baseline = next(
        (r for r in results if r.cell.name == baseline_cell_name),
        results[0],
    )

    out = io.StringIO()
    out.write("# 4-cell comparison report\n\n")
    out.write(
        "Generated by `uoa_detector.backtest.cell_report` "
        "(Phase 3.2.4.3).\n\n",
    )
    out.write(f"**Baseline cell:** `{baseline.cell.name}`\n\n")
    out.write(
        "Deltas in the table below are **raw differences** (cell - "
        "baseline); no statistical significance test is applied at "
        "this stage. Phase 3.3 will introduce the multiple-comparison-"
        "correction methodology.\n\n",
    )

    # Header
    out.write(
        "| cell | total trades | Sharpe | expectancy E | "
        "walk-forward | max DD | overall |\n",
    )
    out.write(
        "|------|------|--------|------|-------|-------|--------|\n",
    )

    for r in results:
        m = r.metrics
        is_baseline = r.cell.name == baseline.cell.name
        out.write(
            f"| `{r.cell.name}`"
            f" | {m.total_trades}"
            f" | {_render_sharpe(m, baseline.metrics, is_baseline)}"
            f" | {_render_value_with_delta(m.expectancy, baseline.metrics.expectancy, is_baseline)}"
            f" | {_render_walk_forward(m, baseline.metrics, is_baseline)}"
            f" | {_render_value_with_delta(m.max_drawdown, baseline.metrics.max_drawdown, is_baseline, lower_is_better=True)}"
            f" | {'**PASS**' if m.overall_pass else '**FAIL**'}"
            " |\n",
        )

    out.write("\n## Per-metric pass/fail breakdown\n\n")
    out.write("| cell | sharpe | expectancy | walk-forward | max DD | total trades |\n")
    out.write("|------|--------|------------|--------------|--------|--------------|\n")
    for r in results:
        by_name = {result.name: result.pass_fail for result in r.metrics.results}
        out.write(
            f"| `{r.cell.name}`"
            f" | {_render_pf(by_name.get('sharpe'))}"
            f" | {_render_pf(by_name.get('expectancy'))}"
            f" | {_render_pf(by_name.get('walk_forward_consistency'))}"
            f" | {_render_pf(by_name.get('max_drawdown'))}"
            f" | {_render_pf(by_name.get('total_trades'))}"
            " |\n",
        )

    out.write("\n## Per-cell run metadata\n\n")
    for r in results:
        out.write(f"- **`{r.cell.name}`** → `run_id={r.run_id}`, ")
        out.write(
            f"open_trades={r.metrics.open_trades}, "
            f"hit_rate={r.metrics.hit_rate:.3f}",
        )
        if r.metrics.sharpe_bonus_flag:
            out.write(", **bonus Sharpe**")
        out.write("\n")

    out.write("\n")
    out.write(_FALSIFICATION_TEXT)

    return out.getvalue()


# ---------------------------------------------------------------------------
# Cell-rendering helpers
# ---------------------------------------------------------------------------


def _render_sharpe(
    cell_metrics: BacktestMetrics,
    baseline_metrics: BacktestMetrics,
    is_baseline: bool,
) -> str:
    """Sharpe column with optional delta + bonus flag."""
    sharpe = cell_metrics.sharpe
    if sharpe is None:
        return "n/a"
    bonus = " ⭐" if cell_metrics.sharpe_bonus_flag else ""
    if is_baseline:
        return f"{sharpe:+.3f}{bonus}"
    base = baseline_metrics.sharpe
    if base is None:
        return f"{sharpe:+.3f}{bonus} (Δ n/a)"
    return f"{sharpe:+.3f}{bonus} (Δ {sharpe - base:+.3f})"


def _render_walk_forward(
    cell_metrics: BacktestMetrics,
    baseline_metrics: BacktestMetrics,
    is_baseline: bool,
) -> str:
    val = cell_metrics.walk_forward_consistency
    if val is None:
        return "n/a"
    if is_baseline:
        return f"{val:.3f}"
    base = baseline_metrics.walk_forward_consistency
    if base is None:
        return f"{val:.3f} (Δ n/a)"
    return f"{val:.3f} (Δ {val - base:+.3f})"


def _render_value_with_delta(
    value: float,
    baseline_value: float,
    is_baseline: bool,
    *,
    lower_is_better: bool = False,
) -> str:
    """Render a numeric value + delta-vs-baseline.

    ``lower_is_better=True`` flips the sign convention for the delta
    so a "better" outcome shows up as a negative delta in plain text;
    we surface a leading +/− indicator either way for readability.
    """
    sign_prefix = "+" if value >= 0 else ""
    val_str = f"{sign_prefix}{value:.3f}"
    if is_baseline:
        return val_str
    delta = value - baseline_value
    delta_str = f"{delta:+.3f}"
    arrow = ""
    if abs(delta) > 1e-9:
        if lower_is_better:  # noqa: SIM108 — clearer as if/else
            arrow = " ↓" if delta < 0 else " ↑"
        else:
            arrow = " ↑" if delta > 0 else " ↓"
    return f"{val_str} (Δ {delta_str}{arrow})"


def _render_pf(pass_fail: str | None) -> str:
    """Render a pass_fail value; bold for PASS, italic for fail/insufficient."""
    if pass_fail is None:
        return "—"
    if pass_fail == "pass":
        return "✅ PASS"
    if pass_fail == "fail":
        return "❌ FAIL"
    return "⚠️ INSUFFICIENT"
